
const tent= [[{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }],
    [{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }],
    [{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }],
    [{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }],
    [{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }],
    [{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    },{ 
        letra:"",
        status:0,
    }]
]

export default tent;